//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCMCheckIn
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stellent.com/CheckIn/", ConfigurationName="UCMCheckIn.CheckInSoap")]
    public interface CheckInSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UCMCheckIn.CheckInUniversalResponse> CheckInUniversalAsync(UCMCheckIn.CheckInUniversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UCMCheckIn.CheckOutResponse> CheckOutAsync(UCMCheckIn.CheckOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UCMCheckIn.CheckOutByNameResponse> CheckOutByNameAsync(UCMCheckIn.CheckOutByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UCMCheckIn.UndoCheckOutResponse> UndoCheckOutAsync(UCMCheckIn.UndoCheckOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UCMCheckIn.UndoCheckOutByNameResponse> UndoCheckOutByNameAsync(UCMCheckIn.UndoCheckOutByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UCMCheckIn.UpdateDocInfoResponse> UpdateDocInfoAsync(UCMCheckIn.UpdateDocInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stellent.com/CheckIn/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UCMCheckIn.CheckInListResponse> CheckInListAsync(UCMCheckIn.CheckInListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class IdcProperty
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckInList
    {
        
        private string dDocNameField;
        
        private string dDocTitleField;
        
        private string dDocTypeField;
        
        private string dDocAuthorField;
        
        private string dSecurityGroupField;
        
        private string dDocAccountField;
        
        private int dIDField;
        
        private bool dIDFieldSpecified;
        
        private int dRevClassIDField;
        
        private bool dRevClassIDFieldSpecified;
        
        private int dRevisionIDField;
        
        private bool dRevisionIDFieldSpecified;
        
        private string dRevLabelField;
        
        private bool dIsCheckedOutField;
        
        private bool dIsCheckedOutFieldSpecified;
        
        private string dCheckoutUserField;
        
        private string dCreateDateField;
        
        private string dInDateField;
        
        private string dOutDateField;
        
        private string dStatusField;
        
        private string dReleaseStateField;
        
        private string dFlag1Field;
        
        private string dWebExtensionField;
        
        private string dProcessingStateField;
        
        private string dMessageField;
        
        private string dReleaseDateField;
        
        private string dRendition1Field;
        
        private string dRendition2Field;
        
        private string dIndexerStateField;
        
        private string dPublishTypeField;
        
        private string dPublishStateField;
        
        private IdcProperty[] customDocMetaDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dDocName
        {
            get
            {
                return this.dDocNameField;
            }
            set
            {
                this.dDocNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string dDocTitle
        {
            get
            {
                return this.dDocTitleField;
            }
            set
            {
                this.dDocTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dDocType
        {
            get
            {
                return this.dDocTypeField;
            }
            set
            {
                this.dDocTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dDocAuthor
        {
            get
            {
                return this.dDocAuthorField;
            }
            set
            {
                this.dDocAuthorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string dSecurityGroup
        {
            get
            {
                return this.dSecurityGroupField;
            }
            set
            {
                this.dSecurityGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string dDocAccount
        {
            get
            {
                return this.dDocAccountField;
            }
            set
            {
                this.dDocAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int dID
        {
            get
            {
                return this.dIDField;
            }
            set
            {
                this.dIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified
        {
            get
            {
                return this.dIDFieldSpecified;
            }
            set
            {
                this.dIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int dRevClassID
        {
            get
            {
                return this.dRevClassIDField;
            }
            set
            {
                this.dRevClassIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevClassIDSpecified
        {
            get
            {
                return this.dRevClassIDFieldSpecified;
            }
            set
            {
                this.dRevClassIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int dRevisionID
        {
            get
            {
                return this.dRevisionIDField;
            }
            set
            {
                this.dRevisionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified
        {
            get
            {
                return this.dRevisionIDFieldSpecified;
            }
            set
            {
                this.dRevisionIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string dRevLabel
        {
            get
            {
                return this.dRevLabelField;
            }
            set
            {
                this.dRevLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool dIsCheckedOut
        {
            get
            {
                return this.dIsCheckedOutField;
            }
            set
            {
                this.dIsCheckedOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIsCheckedOutSpecified
        {
            get
            {
                return this.dIsCheckedOutFieldSpecified;
            }
            set
            {
                this.dIsCheckedOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string dCheckoutUser
        {
            get
            {
                return this.dCheckoutUserField;
            }
            set
            {
                this.dCheckoutUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string dCreateDate
        {
            get
            {
                return this.dCreateDateField;
            }
            set
            {
                this.dCreateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string dInDate
        {
            get
            {
                return this.dInDateField;
            }
            set
            {
                this.dInDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string dOutDate
        {
            get
            {
                return this.dOutDateField;
            }
            set
            {
                this.dOutDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string dStatus
        {
            get
            {
                return this.dStatusField;
            }
            set
            {
                this.dStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string dReleaseState
        {
            get
            {
                return this.dReleaseStateField;
            }
            set
            {
                this.dReleaseStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string dFlag1
        {
            get
            {
                return this.dFlag1Field;
            }
            set
            {
                this.dFlag1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string dWebExtension
        {
            get
            {
                return this.dWebExtensionField;
            }
            set
            {
                this.dWebExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string dProcessingState
        {
            get
            {
                return this.dProcessingStateField;
            }
            set
            {
                this.dProcessingStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string dMessage
        {
            get
            {
                return this.dMessageField;
            }
            set
            {
                this.dMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string dReleaseDate
        {
            get
            {
                return this.dReleaseDateField;
            }
            set
            {
                this.dReleaseDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string dRendition1
        {
            get
            {
                return this.dRendition1Field;
            }
            set
            {
                this.dRendition1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string dRendition2
        {
            get
            {
                return this.dRendition2Field;
            }
            set
            {
                this.dRendition2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string dIndexerState
        {
            get
            {
                return this.dIndexerStateField;
            }
            set
            {
                this.dIndexerStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string dPublishType
        {
            get
            {
                return this.dPublishTypeField;
            }
            set
            {
                this.dPublishTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string dPublishState
        {
            get
            {
                return this.dPublishStateField;
            }
            set
            {
                this.dPublishStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public IdcProperty[] CustomDocMetaData
        {
            get
            {
                return this.customDocMetaDataField;
            }
            set
            {
                this.customDocMetaDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckInListResult
    {
        
        private CheckInList[] checkInListField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CheckInList", Order=0)]
        public CheckInList[] CheckInList
        {
            get
            {
                return this.checkInListField;
            }
            set
            {
                this.checkInListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class StatusInfo
    {
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string statusMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusCodeSpecified
        {
            get
            {
                return this.statusCodeFieldSpecified;
            }
            set
            {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class UpdateDocInfoResult
    {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class UndoCheckOutByNameResult
    {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class UndoCheckOutResult
    {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckOutByNameResult
    {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckOutResult
    {
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class CheckInUniversalResult
    {
        
        private int dIDField;
        
        private bool dIDFieldSpecified;
        
        private int dRevisionIDField;
        
        private bool dRevisionIDFieldSpecified;
        
        private int dRevClassIDField;
        
        private bool dRevClassIDFieldSpecified;
        
        private string dRevLabelField;
        
        private StatusInfo statusInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int dID
        {
            get
            {
                return this.dIDField;
            }
            set
            {
                this.dIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dIDSpecified
        {
            get
            {
                return this.dIDFieldSpecified;
            }
            set
            {
                this.dIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int dRevisionID
        {
            get
            {
                return this.dRevisionIDField;
            }
            set
            {
                this.dRevisionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevisionIDSpecified
        {
            get
            {
                return this.dRevisionIDFieldSpecified;
            }
            set
            {
                this.dRevisionIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int dRevClassID
        {
            get
            {
                return this.dRevClassIDField;
            }
            set
            {
                this.dRevClassIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dRevClassIDSpecified
        {
            get
            {
                return this.dRevClassIDFieldSpecified;
            }
            set
            {
                this.dRevClassIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dRevLabel
        {
            get
            {
                return this.dRevLabelField;
            }
            set
            {
                this.dRevLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public StatusInfo StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.stellent.com/CheckIn/")]
    public partial class IdcFile
    {
        
        private string fileNameField;
        
        private byte[] fileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] fileContent
        {
            get
            {
                return this.fileContentField;
            }
            set
            {
                this.fileContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInUniversal", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckInUniversalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        public string dDocTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=2)]
        public string dDocType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=3)]
        public string dDocAuthor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=4)]
        public string dSecurityGroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=5)]
        public string dDocAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] CustomDocMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=7)]
        public UCMCheckIn.IdcFile primaryFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=8)]
        public UCMCheckIn.IdcFile alternateFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] extraProps;
        
        public CheckInUniversalRequest()
        {
        }
        
        public CheckInUniversalRequest(string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, UCMCheckIn.IdcProperty[] CustomDocMetaData, UCMCheckIn.IdcFile primaryFile, UCMCheckIn.IdcFile alternateFile, UCMCheckIn.IdcProperty[] extraProps)
        {
            this.dDocName = dDocName;
            this.dDocTitle = dDocTitle;
            this.dDocType = dDocType;
            this.dDocAuthor = dDocAuthor;
            this.dSecurityGroup = dSecurityGroup;
            this.dDocAccount = dDocAccount;
            this.CustomDocMetaData = CustomDocMetaData;
            this.primaryFile = primaryFile;
            this.alternateFile = alternateFile;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInUniversalResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckInUniversalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public UCMCheckIn.CheckInUniversalResult CheckInUniversalResult;
        
        public CheckInUniversalResponse()
        {
        }
        
        public CheckInUniversalResponse(UCMCheckIn.CheckInUniversalResult CheckInUniversalResult)
        {
            this.CheckInUniversalResult = CheckInUniversalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckOut", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckOutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public int dID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] extraProps;
        
        public CheckOutRequest()
        {
        }
        
        public CheckOutRequest(int dID, UCMCheckIn.IdcProperty[] extraProps)
        {
            this.dID = dID;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckOutResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckOutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public UCMCheckIn.CheckOutResult CheckOutResult;
        
        public CheckOutResponse()
        {
        }
        
        public CheckOutResponse(UCMCheckIn.CheckOutResult CheckOutResult)
        {
            this.CheckOutResult = CheckOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckOutByName", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckOutByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] extraProps;
        
        public CheckOutByNameRequest()
        {
        }
        
        public CheckOutByNameRequest(string dDocName, UCMCheckIn.IdcProperty[] extraProps)
        {
            this.dDocName = dDocName;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckOutByNameResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckOutByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public UCMCheckIn.CheckOutByNameResult CheckOutByNameResult;
        
        public CheckOutByNameResponse()
        {
        }
        
        public CheckOutByNameResponse(UCMCheckIn.CheckOutByNameResult CheckOutByNameResult)
        {
            this.CheckOutByNameResult = CheckOutByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UndoCheckOut", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UndoCheckOutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public int dID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] extraProps;
        
        public UndoCheckOutRequest()
        {
        }
        
        public UndoCheckOutRequest(int dID, UCMCheckIn.IdcProperty[] extraProps)
        {
            this.dID = dID;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UndoCheckOutResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UndoCheckOutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public UCMCheckIn.UndoCheckOutResult UndoCheckOutResult;
        
        public UndoCheckOutResponse()
        {
        }
        
        public UndoCheckOutResponse(UCMCheckIn.UndoCheckOutResult UndoCheckOutResult)
        {
            this.UndoCheckOutResult = UndoCheckOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UndoCheckOutByName", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UndoCheckOutByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] extraProps;
        
        public UndoCheckOutByNameRequest()
        {
        }
        
        public UndoCheckOutByNameRequest(string dDocName, UCMCheckIn.IdcProperty[] extraProps)
        {
            this.dDocName = dDocName;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UndoCheckOutByNameResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UndoCheckOutByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public UCMCheckIn.UndoCheckOutByNameResult UndoCheckOutByNameResult;
        
        public UndoCheckOutByNameResponse()
        {
        }
        
        public UndoCheckOutByNameResponse(UCMCheckIn.UndoCheckOutByNameResult UndoCheckOutByNameResult)
        {
            this.UndoCheckOutByNameResult = UndoCheckOutByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocInfo", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UpdateDocInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public int dID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        public string dRevLabel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=2)]
        public string dDocName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=3)]
        public string dDocTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=4)]
        public string dDocType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=5)]
        public string dDocAuthor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=6)]
        public string dSecurityGroup;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=7)]
        public string dDocAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] CustomDocMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] extraProps;
        
        public UpdateDocInfoRequest()
        {
        }
        
        public UpdateDocInfoRequest(int dID, string dRevLabel, string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, UCMCheckIn.IdcProperty[] CustomDocMetaData, UCMCheckIn.IdcProperty[] extraProps)
        {
            this.dID = dID;
            this.dRevLabel = dRevLabel;
            this.dDocName = dDocName;
            this.dDocTitle = dDocTitle;
            this.dDocType = dDocType;
            this.dDocAuthor = dDocAuthor;
            this.dSecurityGroup = dSecurityGroup;
            this.dDocAccount = dDocAccount;
            this.CustomDocMetaData = CustomDocMetaData;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDocInfoResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class UpdateDocInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public UCMCheckIn.UpdateDocInfoResult UpdateDocInfoResult;
        
        public UpdateDocInfoResponse()
        {
        }
        
        public UpdateDocInfoResponse(UCMCheckIn.UpdateDocInfoResult UpdateDocInfoResult)
        {
            this.UpdateDocInfoResult = UpdateDocInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInList", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckInListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public bool userOnly;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)]
        public UCMCheckIn.IdcProperty[] extraProps;
        
        public CheckInListRequest()
        {
        }
        
        public CheckInListRequest(bool userOnly, UCMCheckIn.IdcProperty[] extraProps)
        {
            this.userOnly = userOnly;
            this.extraProps = extraProps;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckInListResponse", WrapperNamespace="http://www.stellent.com/CheckIn/", IsWrapped=true)]
    public partial class CheckInListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.stellent.com/CheckIn/", Order=0)]
        public UCMCheckIn.CheckInListResult CheckInListResult;
        
        public CheckInListResponse()
        {
        }
        
        public CheckInListResponse(UCMCheckIn.CheckInListResult CheckInListResult)
        {
            this.CheckInListResult = CheckInListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface CheckInSoapChannel : UCMCheckIn.CheckInSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class CheckInSoapClient : System.ServiceModel.ClientBase<UCMCheckIn.CheckInSoap>, UCMCheckIn.CheckInSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CheckInSoapClient() : 
                base(CheckInSoapClient.GetDefaultBinding(), CheckInSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CheckInSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CheckInSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CheckInSoapClient.GetBindingForEndpoint(endpointConfiguration), CheckInSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CheckInSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CheckInSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CheckInSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CheckInSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CheckInSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UCMCheckIn.CheckInUniversalResponse> UCMCheckIn.CheckInSoap.CheckInUniversalAsync(UCMCheckIn.CheckInUniversalRequest request)
        {
            return base.Channel.CheckInUniversalAsync(request);
        }
        
        public System.Threading.Tasks.Task<UCMCheckIn.CheckInUniversalResponse> CheckInUniversalAsync(string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, UCMCheckIn.IdcProperty[] CustomDocMetaData, UCMCheckIn.IdcFile primaryFile, UCMCheckIn.IdcFile alternateFile, UCMCheckIn.IdcProperty[] extraProps)
        {
            UCMCheckIn.CheckInUniversalRequest inValue = new UCMCheckIn.CheckInUniversalRequest();
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.primaryFile = primaryFile;
            inValue.alternateFile = alternateFile;
            inValue.extraProps = extraProps;
            return ((UCMCheckIn.CheckInSoap)(this)).CheckInUniversalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UCMCheckIn.CheckOutResponse> UCMCheckIn.CheckInSoap.CheckOutAsync(UCMCheckIn.CheckOutRequest request)
        {
            return base.Channel.CheckOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<UCMCheckIn.CheckOutResponse> CheckOutAsync(int dID, UCMCheckIn.IdcProperty[] extraProps)
        {
            UCMCheckIn.CheckOutRequest inValue = new UCMCheckIn.CheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            return ((UCMCheckIn.CheckInSoap)(this)).CheckOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UCMCheckIn.CheckOutByNameResponse> UCMCheckIn.CheckInSoap.CheckOutByNameAsync(UCMCheckIn.CheckOutByNameRequest request)
        {
            return base.Channel.CheckOutByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<UCMCheckIn.CheckOutByNameResponse> CheckOutByNameAsync(string dDocName, UCMCheckIn.IdcProperty[] extraProps)
        {
            UCMCheckIn.CheckOutByNameRequest inValue = new UCMCheckIn.CheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            return ((UCMCheckIn.CheckInSoap)(this)).CheckOutByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UCMCheckIn.UndoCheckOutResponse> UCMCheckIn.CheckInSoap.UndoCheckOutAsync(UCMCheckIn.UndoCheckOutRequest request)
        {
            return base.Channel.UndoCheckOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<UCMCheckIn.UndoCheckOutResponse> UndoCheckOutAsync(int dID, UCMCheckIn.IdcProperty[] extraProps)
        {
            UCMCheckIn.UndoCheckOutRequest inValue = new UCMCheckIn.UndoCheckOutRequest();
            inValue.dID = dID;
            inValue.extraProps = extraProps;
            return ((UCMCheckIn.CheckInSoap)(this)).UndoCheckOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UCMCheckIn.UndoCheckOutByNameResponse> UCMCheckIn.CheckInSoap.UndoCheckOutByNameAsync(UCMCheckIn.UndoCheckOutByNameRequest request)
        {
            return base.Channel.UndoCheckOutByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<UCMCheckIn.UndoCheckOutByNameResponse> UndoCheckOutByNameAsync(string dDocName, UCMCheckIn.IdcProperty[] extraProps)
        {
            UCMCheckIn.UndoCheckOutByNameRequest inValue = new UCMCheckIn.UndoCheckOutByNameRequest();
            inValue.dDocName = dDocName;
            inValue.extraProps = extraProps;
            return ((UCMCheckIn.CheckInSoap)(this)).UndoCheckOutByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UCMCheckIn.UpdateDocInfoResponse> UCMCheckIn.CheckInSoap.UpdateDocInfoAsync(UCMCheckIn.UpdateDocInfoRequest request)
        {
            return base.Channel.UpdateDocInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UCMCheckIn.UpdateDocInfoResponse> UpdateDocInfoAsync(int dID, string dRevLabel, string dDocName, string dDocTitle, string dDocType, string dDocAuthor, string dSecurityGroup, string dDocAccount, UCMCheckIn.IdcProperty[] CustomDocMetaData, UCMCheckIn.IdcProperty[] extraProps)
        {
            UCMCheckIn.UpdateDocInfoRequest inValue = new UCMCheckIn.UpdateDocInfoRequest();
            inValue.dID = dID;
            inValue.dRevLabel = dRevLabel;
            inValue.dDocName = dDocName;
            inValue.dDocTitle = dDocTitle;
            inValue.dDocType = dDocType;
            inValue.dDocAuthor = dDocAuthor;
            inValue.dSecurityGroup = dSecurityGroup;
            inValue.dDocAccount = dDocAccount;
            inValue.CustomDocMetaData = CustomDocMetaData;
            inValue.extraProps = extraProps;
            return ((UCMCheckIn.CheckInSoap)(this)).UpdateDocInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UCMCheckIn.CheckInListResponse> UCMCheckIn.CheckInSoap.CheckInListAsync(UCMCheckIn.CheckInListRequest request)
        {
            return base.Channel.CheckInListAsync(request);
        }
        
        public System.Threading.Tasks.Task<UCMCheckIn.CheckInListResponse> CheckInListAsync(bool userOnly, UCMCheckIn.IdcProperty[] extraProps)
        {
            UCMCheckIn.CheckInListRequest inValue = new UCMCheckIn.CheckInListRequest();
            inValue.userOnly = userOnly;
            inValue.extraProps = extraProps;
            return ((UCMCheckIn.CheckInSoap)(this)).CheckInListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CheckInSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;

                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;

                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CheckInSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.18.17.2:16200/_dav/cs/idcplg");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CheckInSoapClient.GetBindingForEndpoint(EndpointConfiguration.CheckInSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CheckInSoapClient.GetEndpointAddress(EndpointConfiguration.CheckInSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            CheckInSoap,
        }
    }
}
