//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentoPreEditado
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado", ConfigurationName="DocumentoPreEditado.SI_DocumentoPreEditado_OUT")]
    public interface SI_DocumentoPreEditado_OUT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DocumentoPreEditado.CriarDocumentoResponse> CriarDocumentoAsync(DocumentoPreEditado.CriarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DocumentoPreEditado.EstornarDocumentoResponse> EstornarDocumentoAsync(DocumentoPreEditado.EstornarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DocumentoPreEditado.CriarDocumentoResponse> EditarDocumentoAsync(DocumentoPreEditado.EditarDocumentoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_CriarDocumento
    {
        
        private DT_CriarDocumentoCabecalho cabecalhoField;
        
        private DT_CriarDocumentoFornecedor fornecedorField;
        
        private DT_CriarDocumentoRateio[] rateioField;
        
        private DT_CriarDocumentoAdiantamento[] adiantamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_CriarDocumentoCabecalho Cabecalho
        {
            get
            {
                return this.cabecalhoField;
            }
            set
            {
                this.cabecalhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_CriarDocumentoFornecedor Fornecedor
        {
            get
            {
                return this.fornecedorField;
            }
            set
            {
                this.fornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rateio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_CriarDocumentoRateio[] Rateio
        {
            get
            {
                return this.rateioField;
            }
            set
            {
                this.rateioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Adiantamento", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DT_CriarDocumentoAdiantamento[] Adiantamento
        {
            get
            {
                return this.adiantamentoField;
            }
            set
            {
                this.adiantamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_CriarDocumentoCabecalho
    {
        
        private string numProtocoloField;
        
        private string tipoDocGedField;
        
        private string tipoDocSapField;
        
        private string empresaField;
        
        private string aprovadorField;
        
        private string usuarioGedField;
        
        private string textoCabecField;
        
        private string statusProtocoloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumProtocolo
        {
            get
            {
                return this.numProtocoloField;
            }
            set
            {
                this.numProtocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TipoDocGed
        {
            get
            {
                return this.tipoDocGedField;
            }
            set
            {
                this.tipoDocGedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TipoDocSap
        {
            get
            {
                return this.tipoDocSapField;
            }
            set
            {
                this.tipoDocSapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Empresa
        {
            get
            {
                return this.empresaField;
            }
            set
            {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Aprovador
        {
            get
            {
                return this.aprovadorField;
            }
            set
            {
                this.aprovadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string UsuarioGed
        {
            get
            {
                return this.usuarioGedField;
            }
            set
            {
                this.usuarioGedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TextoCabec
        {
            get
            {
                return this.textoCabecField;
            }
            set
            {
                this.textoCabecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string StatusProtocolo
        {
            get
            {
                return this.statusProtocoloField;
            }
            set
            {
                this.statusProtocoloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_RetornoEstorno
    {
        
        private string statusField;
        
        private string mensagemField;
        
        private string fornecedorField;
        
        private string protocoloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Fornecedor
        {
            get
            {
                return this.fornecedorField;
            }
            set
            {
                this.fornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Protocolo
        {
            get
            {
                return this.protocoloField;
            }
            set
            {
                this.protocoloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_EstornarDocumento
    {
        
        private string fornecedorField;
        
        private string protocoloField;
        
        private string statusProcField;
        
        private string usuarioGedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Fornecedor
        {
            get
            {
                return this.fornecedorField;
            }
            set
            {
                this.fornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Protocolo
        {
            get
            {
                return this.protocoloField;
            }
            set
            {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string StatusProc
        {
            get
            {
                return this.statusProcField;
            }
            set
            {
                this.statusProcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string UsuarioGed
        {
            get
            {
                return this.usuarioGedField;
            }
            set
            {
                this.usuarioGedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_Retorno
    {
        
        private string statusField;
        
        private string empresaField;
        
        private string documentoField;
        
        private string exercicioField;
        
        private DT_RetornoMensagem[] mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Empresa
        {
            get
            {
                return this.empresaField;
            }
            set
            {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Exercicio
        {
            get
            {
                return this.exercicioField;
            }
            set
            {
                this.exercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mensagem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public DT_RetornoMensagem[] Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_RetornoMensagem
    {
        
        private string strStatusField;
        
        private string strMensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string strStatus
        {
            get
            {
                return this.strStatusField;
            }
            set
            {
                this.strStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string strMensagem
        {
            get
            {
                return this.strMensagemField;
            }
            set
            {
                this.strMensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_CriarDocumentoFornecedor
    {
        
        private string codFornecedorField;
        
        private string valorField;
        
        private string dataVencField;
        
        private string divisaoField;
        
        private string condicaoPgtoField;
        
        private string textoField;
        
        private string codBarrasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodFornecedor
        {
            get
            {
                return this.codFornecedorField;
            }
            set
            {
                this.codFornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DataVenc
        {
            get
            {
                return this.dataVencField;
            }
            set
            {
                this.dataVencField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Divisao
        {
            get
            {
                return this.divisaoField;
            }
            set
            {
                this.divisaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CondicaoPgto
        {
            get
            {
                return this.condicaoPgtoField;
            }
            set
            {
                this.condicaoPgtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Texto
        {
            get
            {
                return this.textoField;
            }
            set
            {
                this.textoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CodBarras
        {
            get
            {
                return this.codBarrasField;
            }
            set
            {
                this.codBarrasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_CriarDocumentoRateio
    {
        
        private string contaRazaoField;
        
        private string valorField;
        
        private string tipoDespGedField;
        
        private string centroCustoField;
        
        private string ordemField;
        
        private string diagramaRedeField;
        
        private string operacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ContaRazao
        {
            get
            {
                return this.contaRazaoField;
            }
            set
            {
                this.contaRazaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TipoDespGed
        {
            get
            {
                return this.tipoDespGedField;
            }
            set
            {
                this.tipoDespGedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CentroCusto
        {
            get
            {
                return this.centroCustoField;
            }
            set
            {
                this.centroCustoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Ordem
        {
            get
            {
                return this.ordemField;
            }
            set
            {
                this.ordemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DiagramaRede
        {
            get
            {
                return this.diagramaRedeField;
            }
            set
            {
                this.diagramaRedeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Operacao
        {
            get
            {
                return this.operacaoField;
            }
            set
            {
                this.operacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado")]
    public partial class DT_CriarDocumentoAdiantamento
    {
        
        private string protocoloField;
        
        private string empresaField;
        
        private string numAdiantamentoField;
        
        private string exercicioField;
        
        private string itemField;
        
        private string montanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Protocolo
        {
            get
            {
                return this.protocoloField;
            }
            set
            {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Empresa
        {
            get
            {
                return this.empresaField;
            }
            set
            {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NumAdiantamento
        {
            get
            {
                return this.numAdiantamentoField;
            }
            set
            {
                this.numAdiantamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Exercicio
        {
            get
            {
                return this.exercicioField;
            }
            set
            {
                this.exercicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Montante
        {
            get
            {
                return this.montanteField;
            }
            set
            {
                this.montanteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CriarDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado", Order=0)]
        public DocumentoPreEditado.DT_CriarDocumento MT_CriarDocumento;
        
        public CriarDocumentoRequest()
        {
        }
        
        public CriarDocumentoRequest(DocumentoPreEditado.DT_CriarDocumento MT_CriarDocumento)
        {
            this.MT_CriarDocumento = MT_CriarDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CriarDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado", Order=0)]
        public DocumentoPreEditado.DT_Retorno MT_Retorno;
        
        public CriarDocumentoResponse()
        {
        }
        
        public CriarDocumentoResponse(DocumentoPreEditado.DT_Retorno MT_Retorno)
        {
            this.MT_Retorno = MT_Retorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstornarDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado", Order=0)]
        public DocumentoPreEditado.DT_EstornarDocumento MT_EstornarDocumento;
        
        public EstornarDocumentoRequest()
        {
        }
        
        public EstornarDocumentoRequest(DocumentoPreEditado.DT_EstornarDocumento MT_EstornarDocumento)
        {
            this.MT_EstornarDocumento = MT_EstornarDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstornarDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado", Order=0)]
        public DocumentoPreEditado.DT_RetornoEstorno MT_RetornoEstorno;
        
        public EstornarDocumentoResponse()
        {
        }
        
        public EstornarDocumentoResponse(DocumentoPreEditado.DT_RetornoEstorno MT_RetornoEstorno)
        {
            this.MT_RetornoEstorno = MT_RetornoEstorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:FI002_DocumentoPreEditado", Order=0)]
        public DocumentoPreEditado.DT_CriarDocumento MT_EditarDocumento;
        
        public EditarDocumentoRequest()
        {
        }
        
        public EditarDocumentoRequest(DocumentoPreEditado.DT_CriarDocumento MT_EditarDocumento)
        {
            this.MT_EditarDocumento = MT_EditarDocumento;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface SI_DocumentoPreEditado_OUTChannel : DocumentoPreEditado.SI_DocumentoPreEditado_OUT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class SI_DocumentoPreEditado_OUTClient : System.ServiceModel.ClientBase<DocumentoPreEditado.SI_DocumentoPreEditado_OUT>, DocumentoPreEditado.SI_DocumentoPreEditado_OUT
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_DocumentoPreEditado_OUTClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_DocumentoPreEditado_OUTClient.GetBindingForEndpoint(endpointConfiguration), SI_DocumentoPreEditado_OUTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_DocumentoPreEditado_OUTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_DocumentoPreEditado_OUTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_DocumentoPreEditado_OUTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_DocumentoPreEditado_OUTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_DocumentoPreEditado_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentoPreEditado.CriarDocumentoResponse> DocumentoPreEditado.SI_DocumentoPreEditado_OUT.CriarDocumentoAsync(DocumentoPreEditado.CriarDocumentoRequest request)
        {
            return base.Channel.CriarDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentoPreEditado.CriarDocumentoResponse> CriarDocumentoAsync(DocumentoPreEditado.DT_CriarDocumento MT_CriarDocumento)
        {
            DocumentoPreEditado.CriarDocumentoRequest inValue = new DocumentoPreEditado.CriarDocumentoRequest();
            inValue.MT_CriarDocumento = MT_CriarDocumento;
            return ((DocumentoPreEditado.SI_DocumentoPreEditado_OUT)(this)).CriarDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentoPreEditado.EstornarDocumentoResponse> DocumentoPreEditado.SI_DocumentoPreEditado_OUT.EstornarDocumentoAsync(DocumentoPreEditado.EstornarDocumentoRequest request)
        {
            return base.Channel.EstornarDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentoPreEditado.EstornarDocumentoResponse> EstornarDocumentoAsync(DocumentoPreEditado.DT_EstornarDocumento MT_EstornarDocumento)
        {
            DocumentoPreEditado.EstornarDocumentoRequest inValue = new DocumentoPreEditado.EstornarDocumentoRequest();
            inValue.MT_EstornarDocumento = MT_EstornarDocumento;
            return ((DocumentoPreEditado.SI_DocumentoPreEditado_OUT)(this)).EstornarDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocumentoPreEditado.CriarDocumentoResponse> DocumentoPreEditado.SI_DocumentoPreEditado_OUT.EditarDocumentoAsync(DocumentoPreEditado.EditarDocumentoRequest request)
        {
            return base.Channel.EditarDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocumentoPreEditado.CriarDocumentoResponse> EditarDocumentoAsync(DocumentoPreEditado.DT_CriarDocumento MT_EditarDocumento)
        {
            DocumentoPreEditado.EditarDocumentoRequest inValue = new DocumentoPreEditado.EditarDocumentoRequest();
            inValue.MT_EditarDocumento = MT_EditarDocumento;
            return ((DocumentoPreEditado.SI_DocumentoPreEditado_OUT)(this)).EditarDocumentoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;

                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;

                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://mrvsap15.mrvbh.local:50200/XISOAPAdapter/MessageServlet?senderParty=&sende" +
                        "rService=MRVFramework&receiverParty=&receiverService=&interface=SI_DocumentoPreE" +
                        "ditado_OUT&interfaceNamespace=urn:br:com:mrv:FI002_DocumentoPreEditado");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress("https://mrvsap15.mrvbh.local:50201/XISOAPAdapter/MessageServlet?senderParty=&send" +
                        "erService=MRVFramework&receiverParty=&receiverService=&interface=SI_DocumentoPre" +
                        "Editado_OUT&interfaceNamespace=urn:br:com:mrv:FI002_DocumentoPreEditado");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            HTTP_Port,
            
            HTTPS_Port,
        }
    }
}
