//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovadores
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:br:com:mrv:ListarUsuariosSLD", ConfigurationName="Aprovadores.MI_ListarUsuariosSLD_Out")]
    public interface MI_ListarUsuariosSLD_Out
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Aprovadores.MI_ListarUsuariosSLD_OutResponse> MI_ListarUsuariosSLD_OutAsync(Aprovadores.MI_ListarUsuariosSLD_OutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:br:com:mrv:ListarUsuariosSLD")]
    public partial class DT_Request_ListarUsuariosSLD
    {
        
        private string lOGINField;
        
        private string nOMEField;
        
        private string sTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LOGIN
        {
            get
            {
                return this.lOGINField;
            }
            set
            {
                this.lOGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NOME
        {
            get
            {
                return this.nOMEField;
            }
            set
            {
                this.nOMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:br:com:mrv:ListarUsuariosSLD")]
    public partial class DT_Response_ListarUsuariosSLDROW
    {
        
        private string lOGINField;
        
        private string nOMEField;
        
        private string eMAILField;
        
        private string lOGINSAPField;
        
        private string sTATUSField;
        
        private string cPFField;
        
        private string sLDEMAILField;
        
        private string dTAALTField;
        
        private string uSUALTField;
        
        private string dTACRIField;
        
        private string uSUCRIField;
        
        private string tIPOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string LOGIN
        {
            get
            {
                return this.lOGINField;
            }
            set
            {
                this.lOGINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NOME
        {
            get
            {
                return this.nOMEField;
            }
            set
            {
                this.nOMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string EMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOGINSAP
        {
            get
            {
                return this.lOGINSAPField;
            }
            set
            {
                this.lOGINSAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CPF
        {
            get
            {
                return this.cPFField;
            }
            set
            {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string SLDEMAIL
        {
            get
            {
                return this.sLDEMAILField;
            }
            set
            {
                this.sLDEMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DTAALT
        {
            get
            {
                return this.dTAALTField;
            }
            set
            {
                this.dTAALTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string USUALT
        {
            get
            {
                return this.uSUALTField;
            }
            set
            {
                this.uSUALTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string DTACRI
        {
            get
            {
                return this.dTACRIField;
            }
            set
            {
                this.dTACRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string USUCRI
        {
            get
            {
                return this.uSUCRIField;
            }
            set
            {
                this.uSUCRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string TIPO
        {
            get
            {
                return this.tIPOField;
            }
            set
            {
                this.tIPOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MI_ListarUsuariosSLD_OutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:ListarUsuariosSLD", Order=0)]
        public Aprovadores.DT_Request_ListarUsuariosSLD MT_Request_ListarUsuariosSLD;
        
        public MI_ListarUsuariosSLD_OutRequest()
        {
        }
        
        public MI_ListarUsuariosSLD_OutRequest(Aprovadores.DT_Request_ListarUsuariosSLD MT_Request_ListarUsuariosSLD)
        {
            this.MT_Request_ListarUsuariosSLD = MT_Request_ListarUsuariosSLD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MI_ListarUsuariosSLD_OutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:ListarUsuariosSLD", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ROW", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Aprovadores.DT_Response_ListarUsuariosSLDROW[] MT_Response_ListarUsuariosSLD;
        
        public MI_ListarUsuariosSLD_OutResponse()
        {
        }
        
        public MI_ListarUsuariosSLD_OutResponse(Aprovadores.DT_Response_ListarUsuariosSLDROW[] MT_Response_ListarUsuariosSLD)
        {
            this.MT_Response_ListarUsuariosSLD = MT_Response_ListarUsuariosSLD;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface MI_ListarUsuariosSLD_OutChannel : Aprovadores.MI_ListarUsuariosSLD_Out, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class MI_ListarUsuariosSLD_OutClient : System.ServiceModel.ClientBase<Aprovadores.MI_ListarUsuariosSLD_Out>, Aprovadores.MI_ListarUsuariosSLD_Out
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MI_ListarUsuariosSLD_OutClient() : 
                base(MI_ListarUsuariosSLD_OutClient.GetDefaultBinding(), MI_ListarUsuariosSLD_OutClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MI_ListarUsuariosSLD_OutPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MI_ListarUsuariosSLD_OutClient(EndpointConfiguration endpointConfiguration) : 
                base(MI_ListarUsuariosSLD_OutClient.GetBindingForEndpoint(endpointConfiguration), MI_ListarUsuariosSLD_OutClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MI_ListarUsuariosSLD_OutClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MI_ListarUsuariosSLD_OutClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MI_ListarUsuariosSLD_OutClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MI_ListarUsuariosSLD_OutClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MI_ListarUsuariosSLD_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aprovadores.MI_ListarUsuariosSLD_OutResponse> Aprovadores.MI_ListarUsuariosSLD_Out.MI_ListarUsuariosSLD_OutAsync(Aprovadores.MI_ListarUsuariosSLD_OutRequest request)
        {
            return base.Channel.MI_ListarUsuariosSLD_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aprovadores.MI_ListarUsuariosSLD_OutResponse> MI_ListarUsuariosSLD_OutAsync(Aprovadores.DT_Request_ListarUsuariosSLD MT_Request_ListarUsuariosSLD)
        {
            Aprovadores.MI_ListarUsuariosSLD_OutRequest inValue = new Aprovadores.MI_ListarUsuariosSLD_OutRequest();
            inValue.MT_Request_ListarUsuariosSLD = MT_Request_ListarUsuariosSLD;
            return ((Aprovadores.MI_ListarUsuariosSLD_Out)(this)).MI_ListarUsuariosSLD_OutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MI_ListarUsuariosSLD_OutPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MI_ListarUsuariosSLD_OutPort))
            {
                return new System.ServiceModel.EndpointAddress("http://mrvsap03:8000/sap/xi/engine?type=entry&version=3.0&Sender.Service=GED&Inte" +
                        "rface=urn:br:com:mrv:ListarUsuariosSLD^MI_ListarUsuariosSLD_Out");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MI_ListarUsuariosSLD_OutClient.GetBindingForEndpoint(EndpointConfiguration.MI_ListarUsuariosSLD_OutPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MI_ListarUsuariosSLD_OutClient.GetEndpointAddress(EndpointConfiguration.MI_ListarUsuariosSLD_OutPort);
        }
        
        public enum EndpointConfiguration
        {
            
            MI_ListarUsuariosSLD_OutPort,
        }
    }
}
