//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Despesas
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:br:com:mrv:FI005_RetornarDespesasFundoFixo", ConfigurationName="Despesas.SI_RetornarDespesasFF_OUT")]
    public interface SI_RetornarDespesasFF_OUT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Despesas.SI_RetornarDespesasFF_OUTResponse> SI_RetornarDespesasFF_OUTAsync(Despesas.SI_RetornarDespesasFF_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:br:com:mrv:FI005_RetornarDespesasFundoFixo")]
    public partial class DT_Empresa
    {
        
        private string empresaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Empresa
        {
            get
            {
                return this.empresaField;
            }
            set
            {
                this.empresaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:br:com:mrv:FI005_RetornarDespesasFundoFixo")]
    public partial class DT_RetornoTipo
    {
        
        private string statusField;
        
        private string mensagemField;
        
        private DT_RetornoTipoTipoDespesas[] tipoDespesasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TipoDespesas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public DT_RetornoTipoTipoDespesas[] TipoDespesas
        {
            get
            {
                return this.tipoDespesasField;
            }
            set
            {
                this.tipoDespesasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:br:com:mrv:FI005_RetornarDespesasFundoFixo")]
    public partial class DT_RetornoTipoTipoDespesas
    {
        
        private string numTransacaoField;
        
        private string tipoTransacaoField;
        
        private string contaContabilField;
        
        private string nomeTransacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumTransacao
        {
            get
            {
                return this.numTransacaoField;
            }
            set
            {
                this.numTransacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TipoTransacao
        {
            get
            {
                return this.tipoTransacaoField;
            }
            set
            {
                this.tipoTransacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ContaContabil
        {
            get
            {
                return this.contaContabilField;
            }
            set
            {
                this.contaContabilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string NomeTransacao
        {
            get
            {
                return this.nomeTransacaoField;
            }
            set
            {
                this.nomeTransacaoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_RetornarDespesasFF_OUTRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:FI005_RetornarDespesasFundoFixo", Order=0)]
        public Despesas.DT_Empresa MT_Empresa;
        
        public SI_RetornarDespesasFF_OUTRequest()
        {
        }
        
        public SI_RetornarDespesasFF_OUTRequest(Despesas.DT_Empresa MT_Empresa)
        {
            this.MT_Empresa = MT_Empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_RetornarDespesasFF_OUTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:br:com:mrv:FI005_RetornarDespesasFundoFixo", Order=0)]
        public Despesas.DT_RetornoTipo MT_RetornoTipo;
        
        public SI_RetornarDespesasFF_OUTResponse()
        {
        }
        
        public SI_RetornarDespesasFF_OUTResponse(Despesas.DT_RetornoTipo MT_RetornoTipo)
        {
            this.MT_RetornoTipo = MT_RetornoTipo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface SI_RetornarDespesasFF_OUTChannel : Despesas.SI_RetornarDespesasFF_OUT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class SI_RetornarDespesasFF_OUTClient : System.ServiceModel.ClientBase<Despesas.SI_RetornarDespesasFF_OUT>, Despesas.SI_RetornarDespesasFF_OUT
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_RetornarDespesasFF_OUTClient() : 
                base(SI_RetornarDespesasFF_OUTClient.GetDefaultBinding(), SI_RetornarDespesasFF_OUTClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SI_RetornarDespesasFF_OUTPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_RetornarDespesasFF_OUTClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_RetornarDespesasFF_OUTClient.GetBindingForEndpoint(endpointConfiguration), SI_RetornarDespesasFF_OUTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_RetornarDespesasFF_OUTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_RetornarDespesasFF_OUTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_RetornarDespesasFF_OUTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_RetornarDespesasFF_OUTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_RetornarDespesasFF_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Despesas.SI_RetornarDespesasFF_OUTResponse> Despesas.SI_RetornarDespesasFF_OUT.SI_RetornarDespesasFF_OUTAsync(Despesas.SI_RetornarDespesasFF_OUTRequest request)
        {
            return base.Channel.SI_RetornarDespesasFF_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<Despesas.SI_RetornarDespesasFF_OUTResponse> SI_RetornarDespesasFF_OUTAsync(Despesas.DT_Empresa MT_Empresa)
        {
            Despesas.SI_RetornarDespesasFF_OUTRequest inValue = new Despesas.SI_RetornarDespesasFF_OUTRequest();
            inValue.MT_Empresa = MT_Empresa;
            return ((Despesas.SI_RetornarDespesasFF_OUT)(this)).SI_RetornarDespesasFF_OUTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SI_RetornarDespesasFF_OUTPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SI_RetornarDespesasFF_OUTPort))
            {
                return new System.ServiceModel.EndpointAddress("http://mrvsap15.mrvbh.local:50200/sap/xi/engine?type=entry&version=3.0&Sender.Ser" +
                        "vice=MRVFramework&Interface=urn:br:com:mrv:FI005_RetornarDespesasFundoFixo^SI_Re" +
                        "tornarDespesasFF_OUT");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SI_RetornarDespesasFF_OUTClient.GetBindingForEndpoint(EndpointConfiguration.SI_RetornarDespesasFF_OUTPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SI_RetornarDespesasFF_OUTClient.GetEndpointAddress(EndpointConfiguration.SI_RetornarDespesasFF_OUTPort);
        }
        
        public enum EndpointConfiguration
        {
            
            SI_RetornarDespesasFF_OUTPort,
        }
    }
}
